### ISSUE TITLE
slide-cover-title过高导致显示异常

### ISSUE THREAD

**Issue by qiukeren** [garzon/polySlides#1]
![image](https://cloud.githubusercontent.com/assets/2325492/12057139/e7fbca6a-af78-11e5-839f-f02762c2f576.png)

如图……

**Comment by qiukeren** [comment]
去掉height 100%属性后显示似乎正常了
![image](https://cloud.githubusercontent.com/assets/2325492/12057166/17cad2f4-af79-11e5-85ec-6a4e1bd057af.png)

**Comment by garzon** [comment]
https://github.com/garzon/polySlides/pull/2
多谢反馈，已修正
